### PR TITLE
Add a script to create 1Password vaults from a LastPass export CSV

### PR DESCRIPTION
**Pull request by scottisloud**
This PR adds a script that creates 1Password vaults based on the contents of the `grouping` column in a LastPass export. This script does not create 1Password items. 

The value of this script would be for people who prefer, or have already used, our web-based LastPass importer. For example, they can:
1. Import their complete LastPass data into a single 1Password vault using our web importer
2. run this script using the same export data as the input
3. use a 1Password desktop application to move items from the single vault to the appropriate newly-created vault based on the tag our importer applied. 

This may be the best path for people with a large quantity of LastPass Secure Notes, which our web importer can ingest but our import script does not.

### CODE REVIEW

**Review by ag-adampike — CHANGES_REQUESTED** [review]
Looking good so far! The only thing I can see that's missing is a reference to the new script in [`README.md`](https://github.com/1Password/solutions/blob/3183d4bbe95cb3217a884b77208bf1a72471a13a/migration/README.md).

**Comment by scottisloud** [comment]
> Looking good so far! The only thing I can see that's missing is a reference to the new script in [`README.md`](https://github.com/1Password/solutions/blob/3183d4bbe95cb3217a884b77208bf1a72471a13a/migration/README.md).

Updated readme in [e0a6b88](https://github.com/1Password/solutions/pull/18/commits/e0a6b889cf17467d9f9cc6989fc60da69a11792e)

**Comment by jbsoliman** [comment]
Looks good so far to me as well! 

You could probably clean up that output to read a bit cleaner to spit out created vault names line by line; this could look as simple as 

`print(f"The following 1Password vaults were created:")
print("\n".join(created_vault_list))`

**Comment by scottisloud** [comment]
> Looks good so far to me as well!
> 
> You could probably clean up that output to read a bit cleaner to spit out created vault names line by line; this could look as simple as
> 
> `print(f"The following 1Password vaults were created:") print("\n".join(created_vault_list))`

Right on. Fixed up that bit of feedback text and tidied up a few other parts of the readme.

**Pull request merged**
