### PR TITLE
LP Migration: Add dry-run option, for testing without creating items

### PR DESCRIPTION
**Pull request by dancryer**

### CODE REVIEW

**Comment by scottisloud** [comment]
Hi Dan,

Thanks for the PR, and thanks for your patience. It's been a busy time here. I look forward to reviewing this as soon as time permits :) 

Cheers,
Scott

**Comment by scottisloud** [comment]
I've written too much additional code in here to be the lone approver. @black-bryan  and @plttn (who I can't yet assign as a review) are you able to take this for a quick test-drive and review the updated README? 

New changes:
- [x] Prevented vaults from being created when running with `-i --dry-run`. 
- [x] Added `--dry-run` functionality to folder-only mode (`-f --dry-run`) since that seems like a reasonable feature to have in both `-i` and `-f` modes. 
- [x] Updated README to call out `--dry-run` and made a few changes to the "Usage" sections to help people less-familiar with CLI tools understand how to specify options (e.g., not using both `-i` and `--item`)

**Comment by plttn** [comment]
I think my only real nit here with `--dry-run` is that the output format between creating an item, and creating a vault don't necessarily align. 

Creating an item results in `Creating item "Untitled Login" => skipped (dry run)`, but creating a vault logs `Vault "Finance\Team-Meetup" => would be created as "Finance_Team-Meetup"; skipped (dry run)`. In this case, the destination state is on the right hand side of the line, whereas with items, the destination state is on the left. 

I think a better output would be `Creating Vault "Finance_Team-Meetup" => from "Finance\Team-Meetup"; skipped (dry run)`.

Other than that, lgtm.

**Comment by scottisloud** [comment]
As per @plttn's suggestion, some modification to the output:

During a dry-run:

* Feedback for a folder/vault migration is now `From LastPass folder "Shared-read-only/hide-passwords" => created new vault "Shared-read-only_hide-passwords"; skipped (dry run)`
* Feedback for an item is: `"TechCrunch" => migrated; skipped (dry run)`

I took the opportunity to improve (and line up more closely with the dry-run) the feedback for an actual import. Mostly this makes clearer what state the object is in at the moment. E.g., if it's a LastPass folder it's referred to as such.:

* Feedback for a skipped folder is now: `LastPass folder "Shared-xyz" => skipped (ignore shared folders)` (used to be `"Shared-xyz" => skipped (ignore shared folders)` which only implied that "Shared-xyz" is a LastPass folder. 
* Feedback for successfully created items or vaults unchanged. 

@plttn not sure if you have thoughts on these changes or want to give it another once-over. 

@black-bryan if you would like to give this a review, let me know. Otherwise, if you're on board with @plttn's opinion then I'll approve and merge.

**Comment by plttn** [comment]
Happy with those changes for feedback, lgtm.

**Review by scottisloud — APPROVED** [review]
Minor overall changes beyond the originally-filed PR. Tested all possible combinations successfully. Approved.

**Pull request merged**
